### ISSUE TITLE
Will not deploy on Apple Silicon hardware

### ISSUE THREAD

**Issue by yllekz** [MattMckenzy/Casheesh#2]
Hello, I'm getting a critical error when trying to deploy Casheesh in Docker for the first time. Is this an architecture issue?

M1 Mac Mini, macOS Big Sur with Docker Desktop:

```
Unhandled exception. System.IO.IOException: Function not implemented
   at System.IO.FileSystemWatcher.StartRaisingEvents()
   at System.IO.FileSystemWatcher.StartRaisingEventsIfNotDisposed()
   at System.IO.FileSystemWatcher.set_EnableRaisingEvents(Boolean value)
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.TryEnableFileSystemWatcher()
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.CreateFileChangeToken(String filter)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider.Watch(String filter)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.<.ctor>b__1_0()
   at Microsoft.Extensions.Primitives.ChangeToken.OnChange(Func`1 changeTokenProducer, Action changeTokenConsumer)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider..ctor(FileConfigurationSource source)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationSource.Build(IConfigurationBuilder builder)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Microsoft.Extensions.Hosting.HostBuilder.BuildAppConfiguration()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Casheesh.Program.Main(String[] args) in /src/Program.cs:line 12
qemu: uncaught target signal 6 (Aborted) - core dumped
```

This is the YML I'm using for deploying:

```
---
version: "2.1"
services:
  casheesh:
    image: mattmckenzy/casheesh:latest
    container_name: casheesh
    restart: unless-stopped
    ports:
    - 8223:8223
    environment:
    - PUID=501
    - PGID=20
    - TZ=America/New_York
    - ASPNETCORE_URLS=http://+:8223
    volumes:
    - "/Users/me/docker/config/casheesh/data:/data"
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
```

**Comment by MattMckenzy** [comment]
Apologies, I've only compiled and published Casheesh as amd64. Feel free to compile it from source and publish it to docker yourself, however! Let me know if you do and I'll add a link and comment to it in the readme.

**Comment by MattMckenzy** [comment]
I just read that .NET 6 might do the trick for M1 silicon, I'll update it to that when I have a chance soon and let you know. In case you'd like to give it another shot.

**Comment by yllekz** [comment]
Hello, sorry for the delay but I'm still getting the same exact error even after the update. Is it running on .NET 6 or is that still a future-state thing?

**Comment by MattMckenzy** [comment]
Apologies, I hadn't gotten around to it. If you clone the repo and change the project to .NET 6, it might work! I don't think there's any code to change to target .NET 6, it should be a quick thing. You'll probably have an easier time compiling it yourself as well.
